=== xokas/clinicaveterinaria/contenidos/dtd/cabecera.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT cabecera (title_web, metas, direccion, titulo, subtitulo, telefono_fijo, telefono_movil, decoracion, titulo_curiosidades, texto_presentacion)>
<!ELEMENT title_web (#PCDATA)>
<!ELEMENT metas (keywords, description)>
<!ELEMENT keywords (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT direccion (via, codigo_postal, localidad, provincia)>
<!ELEMENT via (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT telefono_fijo (#PCDATA)>
<!ELEMENT telefono_movil (#PCDATA)>
<!ELEMENT decoracion (img_decorativa, img_recargar)>
<!ELEMENT titulo_curiosidades (#PCDATA)>
<!ELEMENT texto_presentacion (#PCDATA)>
<!ELEMENT img_decorativa (#PCDATA)>
<!ELEMENT img_recargar (#PCDATA)>

=== xokas/clinicaveterinaria/contenidos/en/cabecera.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cabecera SYSTEM "../dtd/cabecera.dtd">
<cabecera>
	<title_web>Consulta Veterinaria Gala en Betanzos, A Coruña. Exotic animals, dogs grooming close to Miño.</title_web>
	<metas>
		<keywords>Consulta Veterinaria Gala, Consulta Veterinaria, Clínica Veterinaria, Consulta Veterinaria Betanzos, Consulta Veterinaria Miño, Consulta Veterinaria Paderne, Clínica Veterinaria Betanzos, Veterinary Clinic Paderne, Veterinary Clinic Miño, Betanzos, Veterinary, Exotical animals, Animal care, Veterinary emergency, Grooming service, Betanzos, Miño, A Coruña, Paderne, veterinary in Miño, veterinary in Paderne, veterinary in Betanzos</keywords>
		<description>Consulta Veterinaria Gala in Betanzos, very close to Miño and Paderne, provides a full range of services to you and your pet: 24 hr emergency service, grooming service, home appointments and exotic animals care.</description>
	</metas>
	<direccion>
		<via>Calle Saavedra Meneses 52. Bajo Izq.</via>
		<codigo_postal>15300</codigo_postal>
		<localidad>Betanzos</localidad>
		<provincia>A Coruña</provincia>
	</direccion>
	<titulo>GALA</titulo>
	<subtitulo>Consulta Veterinaria</subtitulo>
	<telefono_fijo>696 949 087</telefono_fijo>
	<telefono_movil>981 775 203</telefono_movil>
	<decoracion>
		<img_decorativa>pin</img_decorativa>
		<img_recargar>reload</img_recargar>
	</decoracion>
	<titulo_curiosidades>Tips for your pet’s care.</titulo_curiosidades>
	<texto_presentacion>Consulta Veterinaria Gala in Betanzos, very close to Miño and Paderne, provides a full range of services to you and your pet: 24 hr emergency service, grooming service, home appointments and exotic animals care.</texto_presentacion>
</cabecera>

=== xokas/clinicaveterinaria/contenidos/es/cabecera.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cabecera SYSTEM "../dtd/cabecera.dtd">
<cabecera>
	<title_web>Consulta Veterinaria Gala en Betanzos, A Coruña. Animales exóticos, peluquería canina cerca de Miño</title_web>
	<metas>
		<keywords>Consulta Veterinaria Gala, Consulta Veterinaria, Clínica Veterinaria, Consulta Veterinaria Betanzos, Consulta Veterinaria Miño, Consulta Veterinaria Paderne, Clínica Veterinaria Betanzos, Clínica Veterinaria Paderne, Clínica Veterinara Miño, Betanzos, Veterinaria, Veterinarios, Animales exóticos, cuidado animales, urgencias veterinarias, peluquería canina, Betanzos, Miño, A Coruña, Paderne, veterinarios en Miño, veterinarios en Paderne, veterinarios en Betanzos</keywords>
		<!--<description>Consulta Veterinaria Gala en Betanzos, ofrecemos un servicio veterinario de consulta, atención a domicilio, urgencias, peluquería canina y atención de animales exóticos, así como el asesoramiento a domicilio de cómo se debe cuidar a todo tipo de animales</description>-->
		<description>La Consulta Veterinaria Gala de Betanzos, muy cerca de Miño y Paderne, dispone de un amplio abanico de servicios a disposición suya y de sus mascotas: urgencias, peluquería canina, atención a domicilio y de animales exóticos.</description>
	</metas>
	<direccion>
		<via>Calle Saavedra Meneses 52. Bajo Izq.</via>
		<codigo_postal>15300</codigo_postal>
		<localidad>Betanzos</localidad>
		<provincia>A Coruña</provincia>
	</direccion>
	<titulo>GALA</titulo>
	<subtitulo>Consulta Veterinaria</subtitulo>
	<telefono_fijo>696 949 087</telefono_fijo>
	<telefono_movil>981 775 203</telefono_movil>
	<decoracion>
		<img_decorativa>chincheta</img_decorativa>
		<img_recargar>recargar</img_recargar>
	</decoracion>
	<titulo_curiosidades>Consejos para tu mascota.</titulo_curiosidades>
	<texto_presentacion>La Consulta Veterinaria Gala de Betanzos, muy cerca de Miño y Paderne, dispone de un amplio abanico de servicios a disposición suya y de sus mascotas: urgencias, peluquería canina, atención a domicilio y de animales exóticos.</texto_presentacion>
</cabecera>

=== xokas/clinicaveterinaria/contenidos/gl/cabecera.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cabecera SYSTEM "../dtd/cabecera.dtd">
<cabecera>
	<title_web>Consulta Veterinaria Gala en Betanzos, A Coruña. Animais exóticos, perruquería canina preto de Miño.</title_web>
	<metas>
		<keywords>Consulta Veterinaria Gala, Consulta Veterinaria, Clínica Veterinaria, Consulta Veterinaria Betanzos, Consulta Veterinaria Miño, Consulta Veterinaria Paderne, Clínica Veterinaria Betanzos, Clínica Veterinaria Paderne, Clínica Veterinara Miño, Betanzos, Veterinaria, Veterinarios, Animales exóticos, cuidado animales, urgencias veterinarias, peluquería canina, Betanzos, Miño, A Coruña, Paderne, veterinarios en Miño, veterinarios en Paderne, veterinarios en Betanzos</keywords>
		<description>A Consulta Veterinaria Gala en Betanzos, moi preto de Miño e Paderne, dispón dunha ampla gama de servizos á disposición das súas mascotas: urxencias, perrucaría canina, atención domiciliaria e de animais exóticos.</description>
	</metas>
	<direccion>
		<via>Calle Saavedra Meneses 52. Bajo Izq.</via>
		<codigo_postal>15300</codigo_postal>
		<localidad>Betanzos</localidad>
		<provincia>A Coruña</provincia>
	</direccion>
	<titulo>GALA</titulo>
	<subtitulo>Consulta Veterinaria</subtitulo>
	<telefono_fijo>696 949 087</telefono_fijo>
	<telefono_movil>981 775 203</telefono_movil>
	<decoracion>
		<img_decorativa>alfinete</img_decorativa>
		<img_recargar>recargar</img_recargar>
	</decoracion>
	<titulo_curiosidades>Consellos para a túa mascota.</titulo_curiosidades>
	<texto_presentacion>A Consulta Veterinaria Gala en Betanzos, moi preto de Miño e Paderne, dispón dunha ampla gama de servizos á disposición das súas mascotas: urxencias, perrucaría canina, atención domiciliaria e de animais exóticos.</texto_presentacion>
</cabecera>
