=== xokas/clinicaveterinaria/contenidos/dtd/imagenes.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT imagenes (imagen+)>
<!ELEMENT imagen (enlace, img, title, alt)>
<!ELEMENT enlace (idPadre, id, texto, href)>
<!ELEMENT img (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT alt (#PCDATA)>
<!ELEMENT idPadre (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT href (#PCDATA)>

=== xokas/clinicaveterinaria/contenidos/en/imagenes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE imagenes SYSTEM "../dtd/imagenes.dtd">
<imagenes>
	<imagen>
		<enlace>
			<idPadre>gala</idPadre>
			<id>quienes_somos</id>
			<texto>About us</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/selva.png</img>
		<title>About us</title>
		<alt>About us</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>gala</idPadre>
			<id>donde_estamos</id>
			<texto>Where we are</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/leo_peque.png</img>
		<title>Where we are</title>
		<alt>Where we are</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>gala</idPadre>
			<id>contacto</id>
			<texto>Contact us</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/pico.png</img>
		<title>Contact us</title>
		<alt>Contact us</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>atencion_a_domicilio</id>
			<texto>Home visit</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/conejo.png</img>
		<title>Home visit</title>
		<alt>Home visit</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>urgencias</id>
			<texto>Emergency</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/waldo.png</img>
		<title>Emergency</title>
		<alt>Emergency</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>peluqueria_canina</id>
			<texto>Grooming service</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/toy.png</img>
		<title>Grooming service</title>
		<alt>Grooming service</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>atencion_de_animales_exoticos</id>
			<texto>Exotic animals care</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/iguana.png</img>
		<title>Exotic animals care</title>
		<alt>Exotic animals care</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>sexaje_de_aves</id>
			<texto>Bird Sexing</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/periquitos.png</img>
		<title>Bird Sexing</title>
		<alt>Bird Sexing</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>tienda_especializada</id>
			<texto>Vet shop</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/toby.png</img>
		<title>Vet shop</title>
		<alt>Vet shop</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>perros_y_gatos</id>
			<texto>Dogs and cats</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/thor_y_zsazsa.png</img>
		<title>Dogs and cats</title>
		<alt>Dogs and cats</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>roedores</id>
			<texto>Rodents</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/nera.png</img>
		<title>Rodents</title>
		<alt>Rodents</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>aves</id>
			<texto>Birds</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/parrot_flickr.png</img>
		<title>Birds</title>
		<alt>Birds</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>reptiles</id>
			<texto>Reptiles</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/tortuga_infopick.png</img>
		<title>Reptiles</title>
		<alt>Reptiles</alt>
	</imagen>
</imagenes>

=== xokas/clinicaveterinaria/contenidos/es/imagenes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE imagenes SYSTEM "../dtd/imagenes.dtd">
<imagenes>
	<imagen>
		<enlace>
			<idPadre>gala</idPadre>
			<id>quienes_somos</id>
			<texto>Quiénes somos</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/selva.png</img>
		<title>Quiénes somos</title>
		<alt>Quiénes somos</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>gala</idPadre>
			<id>donde_estamos</id>
			<texto>Dónde estamos</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/leo_peque.png</img>
		<title>Dónde estamos</title>
		<alt>Dónde estamos</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>gala</idPadre>
			<id>contacto</id>
			<texto>Contacto</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/pico.png</img>
		<title>Contacto</title>
		<alt>Contacto</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>atencion_a_domicilio</id>
			<texto>Atención a domicilio</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/conejo.png</img>
		<title>Atención a domicilio</title>
		<alt>Atención a domicilio</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>urgencias</id>
			<texto>Urgencias</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/waldo.png</img>
		<title>Urgencias</title>
		<alt>Urgencias</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>peluqueria_canina</id>
			<texto>Peluquería canina</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/toy.png</img>
		<title>Peluquería canina</title>
		<alt>Peluquería canina</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>atencion_de_animales_exoticos</id>
			<texto>Atención de animales exóticos</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/iguana.png</img>
		<title>Atención de animales exóticos</title>
		<alt>Atención de animales exóticos</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>sexaje_de_aves</id>
			<texto>Sexaje de aves</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/periquitos.png</img>
		<title>Sexaje de aves</title>
		<alt>Sexaje de aves</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>tienda_especializada</id>
			<texto>Tienda especializada</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/toby.png</img>
		<title>Tienda especializada</title>
		<alt>Tienda especializada</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>perros_y_gatos</id>
			<texto>Perros y gatos</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/thor_y_zsazsa.png</img>
		<title>Perros y gatos</title>
		<alt>Perros y gatos</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>roedores</id>
			<texto>Roedores</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/nera.png</img>
		<title>Roedores</title>
		<alt>Roedores</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>aves</id>
			<texto>Aves</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/parrot_flickr.png</img>
		<title>Aves</title>
		<alt>Aves</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>reptiles</id>
			<texto>Reptiles</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/tortuga_infopick.png</img>
		<title>Reptiles</title>
		<alt>Reptiles</alt>
	</imagen>
</imagenes>

=== xokas/clinicaveterinaria/contenidos/gl/imagenes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE imagenes SYSTEM "../dtd/imagenes.dtd">
<imagenes>
	<imagen>
		<enlace>
			<idPadre>gala</idPadre>
			<id>quienes_somos</id>
			<texto>Quen somos</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/selva.png</img>
		<title>Quen somos</title>
		<alt>Quen somos</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>gala</idPadre>
			<id>donde_estamos</id>
			<texto>Onde estamos</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/leo_peque.png</img>
		<title>Onde estamos</title>
		<alt>Onde estamos</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>gala</idPadre>
			<id>contacto</id>
			<texto>Contacto</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/pico.png</img>
		<title>Contacto</title>
		<alt>Contacto</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>atencion_a_domicilio</id>
			<texto>Atención a domicilio</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/conejo.png</img>
		<title>Atención a domicilio</title>
		<alt>Atención a domicilio</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>urgencias</id>
			<texto>Urxencias</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/waldo.png</img>
		<title>Urxencias</title>
		<alt>Urxencias</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>peluqueria_canina</id>
			<texto>Perruquería canina</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/toy.png</img>
		<title>Perruquería canina</title>
		<alt>Perruquería canina</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>atencion_de_animales_exoticos</id>
			<texto>Atención de animais exóticos.</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/iguana.png</img>
		<title>Atención de animais exóticos.</title>
		<alt>Atención de animais exóticos.</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>sexaje_de_aves</id>
			<texto>Determinación de sexo en aves.</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/periquitos.png</img>
		<title>Determinación de sexo en aves.</title>
		<alt>Determinación de sexo en aves.</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>servicios</idPadre>
			<id>tienda_especializada</id>
			<texto>Tenda especializada</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/toby.png</img>
		<title>Tenda especializada</title>
		<alt>Tenda especializada</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>perros_y_gatos</id>
			<texto>Cans e gatos</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/thor_y_zsazsa.png</img>
		<title>Cans e gatos</title>
		<alt>Cans e gatos</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>roedores</id>
			<texto>Roedores</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/nera.png</img>
		<title>Roedores</title>
		<alt>Roedores</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>aves</id>
			<texto>Aves</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/parrot_flickr.png</img>
		<title>Aves</title>
		<alt>Aves</alt>
	</imagen>
	<imagen>
		<enlace>
			<idPadre>consejos</idPadre>
			<id>reptiles</id>
			<texto>Reptiles</texto>
			<href>#</href>
		</enlace>
		<img>/img/fotos/tortuga_infopick.png</img>
		<title>Reptiles</title>
		<alt>Reptiles</alt>
	</imagen>
</imagenes>
